version: '3.9'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - ./server:/app
    env_file:
      - .env
    restart: always
    networks:
      - internal

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "443:3000"
    volumes:
      - ./client:/app
    env_file:
      - .env
    restart: always
    networks:
      - internal

networks:
  internal:
    driver: bridge
