name: Deploy to Azure VM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Deploy to Azure VM
        run: |
          az vm run-command invoke \
            --command-id RunShellScript \
            --name folio-vm \
            --resource-group folio-resource \
            --scripts "export HOME=/home/azureuser && git config --global --add safe.directory /home/azureuser/Folio && cd /home/azureuser/Folio && git pull origin main && cd /home/azureuser/Folio/server && sudo docker build -t folio . && sudo docker run -d --name folio folio"
